# Change baseurl before deploy
baseurl = "https://techlog.sonyakun.com"
languageCode = "ja-jp"
paginate = 5
title = "TechLog"
enableEmoji = true

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "ja"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false
googleAnalytics = "G-6ED9KVS5VJ"
# Change it to your Disqus shortname before using
disqusShortname = "vrc-blog"

enableRobotsTXT = true

[sitemap]
  changeFreq = ''
  disable = false
  filename = 'sitemap.xml'
  priority = -1
